import { RouterModule, Routes } from '@angular/router';
import { AuthComponent } from './auth.component';
import { DashboardCrmComponent } from '../dashboard-crm/dashboard-crm.component';
import { AllPharmaciesComponent } from '../patient/pharmacy/all-pharmacies/all-pharmacies.component';
import { MyPharmaciesComponent } from '../patient/pharmacy/my-pharmacies/my-pharmacies.component';
import { DermatologistAppointmentHistoryComponent } from '../patient/dermatologist/dermatologist-appointment-history/dermatologist-appointment-history.component';
import { DermatologistScheduledAppointmentsComponent } from '../patient/dermatologist/dermatologist-scheduled-appointments/dermatologist-scheduled-appointments.component';
import { DermatologistSchedulingComponent } from '../patient/dermatologist/dermatologist-scheduling/dermatologist-scheduling.component';
import { PatientProfileComponent } from '../patient/patient-profile/patient-profile.component';
import { PharmacistCounselingHistoryComponent } from '../patient/pharmacist/pharmacist-counseling-history/pharmacist-counseling-history.component';
import { PharmacistScheduledCounselingComponent } from '../patient/pharmacist/pharmacist-scheduled-counseling/pharmacist-scheduled-counseling.component';
import { PharmacistSchedulingComponent } from '../patient/pharmacist/pharmacist-scheduling/pharmacist-scheduling.component';
import { ReservedDrugsComponent } from '../patient/drugs/reserved-drugs/reserved-drugs.component';
import { DispensedDrugsComponent } from '../patient/drugs/dispensed-drugs/dispensed-drugs.component';
import { TakingDrugsComponent } from '../patient/drugs/taking-drugs/taking-drugs.component';
import { EPrescriptionComponent } from '../patient/e-prescription/e-prescription.component';
import { PenaltyComponent } from '../patient/penalty/penalty.component';
import { ComplaintsComponent } from '../patient/complaints/complaints.component';
import { DermatologistWorkCalendarComponent } from '../dermatologist/dermatologist-work-calendar/dermatologist-work-calendar.component';
import { DermatologistPatientsComponent } from '../dermatologist/dermatologist-patients/dermatologist-patients.component';
import { DermatologistStartAppointmentComponent } from '../dermatologist/dermatologist-start-appointment/dermatologist-start-appointment.component';
import { DermatologistNewAppointmentComponent } from '../dermatologist/dermatologist-new-appointment/dermatologist-new-appointment.component';
import { DermatologistVacationRequestComponent } from '../dermatologist/dermatologist-vacation-request/dermatologist-vacation-request.component';
import { DermatologistAbsenceRequestComponent } from '../dermatologist/dermatologist-absence-request/dermatologist-absence-request.component';
import { DermatologistProfileComponent } from '../dermatologist/dermatologist-profile/dermatologist-profile.component';
import { PharmacyAdministratorMyPharmacyComponent } from '../pharmacy-administrator/pharmacy-administrator-my-pharmacy/pharmacy-administrator-my-pharmacy.component';
import { FreeAppointmentsComponent } from '../pharmacy-administrator/free-appointments/free-appointments.component';
import { BusinessReportComponent } from '../pharmacy-administrator/business-report/business-report.component';
import { AllAvailableMedicinesComponent } from '../pharmacy-administrator/all-available-medicines/all-available-medicines.component';
import { AddMedicineComponent } from '../pharmacy-administrator/add-medicine/add-medicine.component';
import { RequestForMedicinesComponent } from '../pharmacy-administrator/request-for-medicines/request-for-medicines.component';
import { AllPharmacistsComponent } from '../pharmacy-administrator/all-pharmacists/all-pharmacists.component';
import { AddPharmacistComponent } from '../pharmacy-administrator/add-pharmacist/add-pharmacist.component';
import { AllDermatologistsComponent } from '../pharmacy-administrator/all-dermatologists/all-dermatologists.component';
import { AddDermatologistComponent } from '../pharmacy-administrator/add-dermatologist/add-dermatologist.component';
import { AllOrderListsComponent } from '../pharmacy-administrator/all-order-lists/all-order-lists.component';
import { CreateOrderListComponent } from '../pharmacy-administrator/create-order-list/create-order-list.component';


export const appRoutes: Routes = [{
    path: '', component: AuthComponent, children: [
        { path: 'dashboard', component: DashboardCrmComponent },
        { path: 'patient/pharmacy/all-pharmacies', component: AllPharmaciesComponent },
        { path: 'patient/pharmacy/my-pharmacies', component: MyPharmaciesComponent },
        { path: 'patient/dermatologist/dermatologist-appointment-history', component: DermatologistAppointmentHistoryComponent },
        { path: 'patient/dermatologist/dermatologist-scheduled-appointments', component: DermatologistScheduledAppointmentsComponent },
        { path: 'patient/dermatologist/dermatologist-scheduling', component: DermatologistSchedulingComponent },
        { path: 'patient/pharmacist/pharmacist-counseling-history', component: PharmacistCounselingHistoryComponent },
        { path: 'patient/pharmacist/pharmacist-scheduled-counseling', component: PharmacistScheduledCounselingComponent },
        { path: 'patient/pharmacist/pharmacist-scheduling', component: PharmacistSchedulingComponent },
        { path: 'patient/drugs/reserved-drugs', component: ReservedDrugsComponent },
        { path: 'patient/drugs/dispensed-drugs', component: DispensedDrugsComponent },
        { path: 'patient/drugs/taking-drugs', component: TakingDrugsComponent },
        { path: 'patient/e-prescription', component: EPrescriptionComponent },
        { path: 'patient/penalty', component: PenaltyComponent },
        { path: 'patient/complaints', component: ComplaintsComponent },
        { path: 'patient/patient-profile', component: PatientProfileComponent },
        { path: 'dermatologist/work-calendar', component: DermatologistWorkCalendarComponent },
        { path: 'dermatologist/patients', component: DermatologistPatientsComponent },
        { path: 'dermatologist/start-appointment', component: DermatologistStartAppointmentComponent },
        { path: 'dermatologist/new-appointment', component: DermatologistNewAppointmentComponent },
        { path: 'dermatologist/vacation-request', component: DermatologistVacationRequestComponent },
        { path: 'dermatologist/absence-request', component: DermatologistAbsenceRequestComponent },
        { path: 'dermatologist/profile', component: DermatologistProfileComponent },
        { path: 'pharmacy-administrator/my-pharmacy', component: PharmacyAdministratorMyPharmacyComponent },
        { path: 'pharmacy-administrator/free-appointments', component: FreeAppointmentsComponent },
        { path: 'pharmacy-administrator/business-report', component: BusinessReportComponent },
        { path: 'pharmacy-administrator/all-available-medicines', component: AllAvailableMedicinesComponent },
        { path: 'pharmacy-administrator/add-medicine', component: AddMedicineComponent },
        { path: 'pharmacy-administrator/request-for-medicines', component: RequestForMedicinesComponent },
        { path: 'pharmacy-administrator/all-pharmacists', component: AllPharmacistsComponent },
        { path: 'pharmacy-administrator/add-pharmacist', component: AddPharmacistComponent },
        { path: 'pharmacy-administrator/all-dermatologists', component: AllDermatologistsComponent },
        { path: 'pharmacy-administrator/add-dermatologist', component: AddDermatologistComponent },
        { path: 'pharmacy-administrator/all-order-lists', component: AllOrderListsComponent },
        { path: 'pharmacy-administrator/create-order-list', component: CreateOrderListComponent },
        { path: 'scrumboard', loadChildren: () => import('../scrumboard/scrumboard.module').then(m => m.ScrumboardModule) },
    ]
}];
 
